name: manual trigger speficy value and user
env:
  testvar: 1234
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'check the value'
        required: true
        default: '${{ env.testvar }}'


jobs:
  job1:
#    if: github.event.inputs.value=='dev' || github.event.inputs.value=='SIT' || ((github.event.inputs.value=='Test' || github.event.inputs.value=='UAT' || github.event.inputs.value=='Prod') && github.actor=='zwdgg1985')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo ${{ github.event.inputs.value }}
